config/routes.rb
HitsApp::Application.routes.draw do

  get "players/index"
  match '/players/search', :controller => 'players', :action => 'search'
  match '/players/slugging', :controller => 'players', :action => 'slugging'
  match '/players/fantasy', :controller => 'players', :action => 'fantasy'
  match '/players/triple_crown', :controller => 'players', :action => 'triple_crown'
  resources :players
  root :to => 'players#index'
  resource :players do
      collection do
         get :search
         post :search
         get :slugging
         post :slugging
         get :fantasy
         post :fantasy
         get :triple_crown
         post :triple_crown
      end
  end 

end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :AB, :CS, :G, :H, :HR, :R, :RBI, :SB, :THREEB, :TWOB, :playerID, :teamID, :yearID
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
     @title = "All Players"
     @players = Player.all
  end

  def show
      @player = Player.find(params[:id])
  end

  def search
      @title = "Search Players"
      @players = Player.where('AB > 200').where('yearID BETWEEN 2009 and 2010').order('H/AB DESC')
  end

  def slugging
      @title = "Slugging Percentage"
      @players = Player.where('teamID = "OAK"').where('yearID = 2007').order('((H - TWOB - THREEB - HR) + (2 * TWOB) + (3 * THREEB) + (4 * HR)) / AB  DESC')
  end

  def fantasy
      @title = "Fantasy Scoring"
      @players = Player.where('yearID BETWEEN 2011 and 2012').where('AB > 500').order('((HR * 4) + RBI + SB + CS) DESC').limit(5)
  end

  def triple_crown
      @playerH_AB = Player.where('yearID BETWEEN 2011 and 2012').order('(H/AB) DESC').first
      @playerHR = Player.where('yearID BETWEEN 2011 and 2012').order('HR DESC').first
      @playerRBI = Player.where('yearID BETWEEN 2011 and 2012').order('RBI DESC').first

      if (@playerH_AB == @playerHR && @playerHR == @playerRBI)
         @title = "Triple Crown"
         @players = @playerHR
         
      else
         flash.now[:success] = "No winner"
         @players = Player.all
         render 'index'
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HitsApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<section>
  <% flash.each do |key, value| %>
     <div class="flash <%= key %>"><%= value %></div>
  <% end %>
</section>
<%= yield %>

</body>
</html>

app/views/players/fantasy.html.erb
<title>Fantasy Scoring</title>
<h1>Fantasy Scoring</h1>

<%= link_to "All Players", players_path %>
<ul>
  <li>PlayerID,yearID,AB,HR,RBI,SB,CS,Fantasy Scoring</li>
  <% @players.each do |player| %>
    <li>
       <%= player.playerID %>
       <%= player.yearID %>
       <%= player.AB %>
       <%= player.HR %>
       <%= player.RBI %>
       <%= player.SB %>
       <%= player.CS %>
       <%= ((player.HR).to_f * 4 + (player.RBI).to_f + (player.SB).to_f + (player.CS).to_f).round(5) %>
    </li>
  <% end %>
</ul>

app/views/players/index.html.erb
<title>All Players</title>
<h1>All Players</h1>

<%= link_to "Search Players", search_players_path %><br />
<%= link_to "Slugging Percentage", slugging_players_path %><br />
<%= link_to "Fantasy Scoring", fantasy_players_path %><br />
<%= link_to "Triple Crown", triple_crown_players_path %><br />
<ul>
  <% @players.each do |player| %>
    <li>
     <%= link_to player.playerID, player %>
    </li>
  <% end %>
</ul>

app/views/players/search.html.erb
<title>Search Players</title>
<h1>Search Players</h1>

<%= link_to "All Players", players_path %>
<ul>
  <li>PlayerID,yearID,H,AB,H/AB</li>
  <% @players.each do |player| %>
    <li>
       <%= player.playerID %>
       <%= player.yearID %>
       <%= player.H %>
       <%= player.AB %>
       <%= ((player.H).to_f/(player.AB).to_f).round(5) %> 
    </li>
  <% end %>
</ul>

app/views/players/show.html.erb
<title>Show Player</title>
<h1>Show Player</h1>

<h1><%= @player.id %></h1><h1><%= @player.playerID %></h1>, <h1><%= @player.yearID %></h1>, <h1><%= @player.teamID %></h1>, <h1><%= @player.G %></h1>

app/views/players/slugging.html.erb
<title>Slugging Percentage</title>
<h1>Slugging Percentage</h1>

<%= link_to "All Players", players_path %>
<ul>
  <li>PlayerID,TeamID,YearID, Slugging</li>
  <% @players.each do |player| %>
    <li>
       <%= player.playerID %>
       <%= player.teamID %>
       <%= player.yearID %>
       <%= (((player.H).to_f - (player.TWOB).to_f - (player.THREEB).to_f - (player.HR).to_f + 2 * (player.TWOB).to_f + 3 * (player.THREEB).to_f + 4 * (player.HR).to_f) / (player       .AB).to_f).round(4) %>
    </li>
  <% end %>
</ul>

app/views/players/triple_crown.html.erb
<title>Triple Crown</title>
<h1>Triple Crown</h1>

<%= link_to "All Players", players_path %>
<ul>
  <li>PlayerID,yearID,Batting Average,HR,RBI</li>
    <li>
       <%= @players.playerID %>
       <%= @players.yearID %>
       <%= ((@players.H).to_f/(@players.AB).to_f) %> 
       <%= @players.HR %>
       <%= @players.RBI %>
    </li>
</ul>